import Head from "next/head";
import "./globals.css";

export const metadata = {
  title: "Audiophile Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" type="image/png" sizes="32x32" href="/img/favicon-32x32.png" />
      </Head>
      <body>{children}</body>
    </html>
  );
}
